/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/circuits/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Circuits */
        get: operations["list_circuits_circuits__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/circuits/{circuit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Circuit */
        get: operations["get_circuit_circuits__circuit_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/circuits/{circuit_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Circuit Stats */
        get: operations["get_circuit_stats_circuits__circuit_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/circuits/{circuit_id}/lap-record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lap Record */
        get: operations["get_lap_record_circuits__circuit_id__lap_record_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/race-weekends/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Race Weekends
         * @description The race calendar for a season, e.g. /race-weekends/?season=2026.
         */
        get: operations["list_race_weekends_race_weekends__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/race-weekends/{season}/{round_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Race Weekend */
        get: operations["get_race_weekend_race_weekends__season___round_number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drivers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Drivers
         * @description The driver grid for a season, e.g. /drivers/?season=2026.
         */
        get: operations["list_drivers_drivers__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/standings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Standings
         * @description Championship standings, e.g. /standings/?season=2026&type=constructor.
         *
         *     Omit `after_round` to get the latest standings available for the season.
         */
        get: operations["list_standings_standings__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Strategies
         * @description Generated strategy options for a race weekend, each with its ordered stints.
         *
         *     e.g. /strategies/?season=2026&round=11. Returns an empty list if the weekend
         *     has no strategies generated yet.
         */
        get: operations["list_strategies_strategies__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/weather/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Weather
         * @description Per-session weather forecast for a race weekend.
         *
         *     e.g. /weather/?season=2026&round=11. Returns an empty list if no forecast
         *     has been loaded for the weekend yet.
         */
        get: operations["list_weather_weather__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/race-results/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Race Results
         * @description All race finishing positions for a season, e.g. /race-results/?season=2026.
         *
         *     Ordered by round then position. Returns an empty list if none loaded yet.
         */
        get: operations["list_race_results_race_results__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Circuit */
        Circuit: {
            /** Circuit Id */
            circuit_id: string;
            /** Country */
            country: string;
            /** Track Length Km */
            track_length_km: number;
            /** Num Corners */
            num_corners: number;
            /** Num Laps */
            num_laps: number;
            /** Sm Zones */
            sm_zones: number;
            /** Jolpica Id */
            jolpica_id: string;
            /** Fastf1 Location */
            fastf1_location: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Layout Since Year */
            layout_since_year?: number | null;
            /** Track Outline */
            track_outline?: string | null;
        };
        /** CircuitStats */
        CircuitStats: {
            /** Id */
            id?: number | null;
            /** Circuit Id */
            circuit_id: string;
            /** Season */
            season: number;
            /** Sc Probability */
            sc_probability: number;
            /** Red Flag Probability */
            red_flag_probability: number;
            /** Pit Loss Normal */
            pit_loss_normal: number;
            /** Pit Loss Sc */
            pit_loss_sc: number;
            /** Pit Loss Vsc */
            pit_loss_vsc: number;
            /** Undercut Strength */
            undercut_strength: number;
            /** Overcut Strength */
            overcut_strength: number;
            /** Updated At */
            updated_at?: string | null;
        };
        /** Driver */
        Driver: {
            /** Id */
            id?: number | null;
            /** Driver Id */
            driver_id: string;
            /** Full Name */
            full_name: string;
            /** Nationality */
            nationality: string;
            /** Team */
            team: string;
            /** Season */
            season: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LapRecord */
        LapRecord: {
            /** Id */
            id?: number | null;
            /** Circuit Id */
            circuit_id: string;
            /** Driver */
            driver: string;
            /** Year */
            year: number;
            /** Lap Time Seconds */
            lap_time_seconds: number;
        };
        /** RaceResult */
        RaceResult: {
            /** Id */
            id?: number | null;
            /** Circuit Id */
            circuit_id: string;
            /** Season */
            season: number;
            /** Round Number */
            round_number: number;
            /** Position */
            position: number;
            /** Driver Id */
            driver_id: string;
            /** Team */
            team: string;
        };
        /** RaceWeekend */
        RaceWeekend: {
            /** Id */
            id?: number | null;
            /** Circuit Id */
            circuit_id: string;
            /** Season */
            season: number;
            /** Round Number */
            round_number: number;
            /** Event Name */
            event_name: string;
            /**
             * Race Date
             * Format: date
             */
            race_date: string;
            /** Is Sprint */
            is_sprint: boolean;
            /** Soft Compound */
            soft_compound: string;
            /** Medium Compound */
            medium_compound: string;
            /** Hard Compound */
            hard_compound: string;
        };
        /** Standing */
        Standing: {
            /** Id */
            id?: number | null;
            /** Season */
            season: number;
            /** After Round */
            after_round: number;
            /** Type */
            type: string;
            /** Position */
            position: number;
            /** Name */
            name: string;
            /** Points */
            points: number;
        };
        /** StrategyStint */
        StrategyStint: {
            /** Id */
            id?: number | null;
            /** Strategy Id */
            strategy_id: number;
            /** Stint Order */
            stint_order: number;
            /** Compound */
            compound: string;
            /** Pit Lap Window Start */
            pit_lap_window_start: number;
            /** Pit Lap Window End */
            pit_lap_window_end: number;
        };
        /**
         * StrategyWithStints
         * @description A strategy plus its ordered stints — API read shape (not a seed/upsert type).
         */
        StrategyWithStints: {
            /** Id */
            id?: number | null;
            /** Race Weekend Id */
            race_weekend_id: number;
            /** Is Base */
            is_base: boolean;
            /** Num Stops */
            num_stops: number;
            /** Label */
            label: string;
            /** Updated At */
            updated_at?: string | null;
            /**
             * Stints
             * @default []
             */
            stints: components["schemas"]["StrategyStint"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeatherForecast */
        WeatherForecast: {
            /** Id */
            id?: number | null;
            /** Race Weekend Id */
            race_weekend_id: number;
            /** Session Name */
            session_name: string;
            /**
             * Session Date
             * Format: date
             */
            session_date: string;
            /** Condition */
            condition: string;
            /** Temp High C */
            temp_high_c: number;
            /** Temp Low C */
            temp_low_c: number;
            /** Rain Probability */
            rain_probability: number;
            /** Wind Speed Kph */
            wind_speed_kph: number;
            /** Updated At */
            updated_at?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_circuits_circuits__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Circuit"][];
                };
            };
        };
    };
    get_circuit_circuits__circuit_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                circuit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Circuit"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_circuit_stats_circuits__circuit_id__stats_get: {
        parameters: {
            query: {
                season: number;
            };
            header?: never;
            path: {
                circuit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CircuitStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lap_record_circuits__circuit_id__lap_record_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                circuit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LapRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_race_weekends_race_weekends__get: {
        parameters: {
            query: {
                season: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RaceWeekend"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_race_weekend_race_weekends__season___round_number__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season: number;
                round_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RaceWeekend"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_drivers_drivers__get: {
        parameters: {
            query: {
                season: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Driver"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_standings_standings__get: {
        parameters: {
            query: {
                season: number;
                type?: string;
                after_round?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Standing"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_strategies_strategies__get: {
        parameters: {
            query: {
                season: number;
                round: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyWithStints"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_weather_weather__get: {
        parameters: {
            query: {
                season: number;
                round: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeatherForecast"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_race_results_race_results__get: {
        parameters: {
            query: {
                season: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RaceResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
